
#:import utils kivy.utils

<StartWindow>: 
      
    GridLayout:
        cols: 1
        rows: 2
     
        Button:        
            text: 'Host'
            background_color: utils.get_color_from_hex('#3585DA')
            font_size: 100

            on_press: 
                root.host()

        Button:
            text: 'Connect'
            background_color: utils.get_color_from_hex('#59C1E8')
            font_size: 100

            on_press: 
                root.client()